name: geojson
description: Utilities to work with geojson data. Parser with a reactive api,
  search and geofencing
homepage: https://github.com/synw/geojson
version: 2.0.0

environment:
  sdk: ">=3.0.0 <5.0.0"

dependencies:
  geodesy: ^0.10.2
  iso: ^1.0.0
  pedantic: ^1.11.1

dev_dependencies:
  extra_pedantic: '>=1.3.0 <5.0.0'
  test: '>=1.17.4 <1.25.0'
